### ISSUE TITLE
CUDA error: CUBLAS_STATUS_INVALID_VALUE

### ISSUE THREAD

**Issue by kameel2311** [lyclyc52/NeRF_RPN#21]
Thank you for this work. I was trying to make an initial run but currently stuck at this error when trying to run the following setting:
```
set -x
set -e
DATA_ROOT=/hypersim_rpn_data
python3 -u run_rpn.py \
--mode "eval" \
--dataset_name hypersim \
--resolution 160 \
--backbone_type resnet \
--features_path ${DATA_ROOT}/features \
--boxes_path ${DATA_ROOT}/obb \
--dataset_split ${DATA_ROOT}/hypersim_split.npz \
--save_path ./results/resnet_anchor_swins \
--checkpoint /hypersim_anchor_resnet50.pt \
--rpn_nms_thresh 0.3 \
--normalize_density \
--rotated_bbox \
--batch_size 1 \
--gpus 0 
```
Where the following error is shown:
```
Traceback (most recent call last):
  File "/home/kameel/Repos/NeRF_RPN/nerf_rpn/run_rpn.py", line 1063, in <module>
    main()
  File "/home/kameel/Repos/NeRF_RPN/nerf_rpn/run_rpn.py", line 1047, in main
    trainer.eval(trainer.test_set)
  File "/home/kameel/anaconda3/envs/nerfrpn/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/kameel/Repos/NeRF_RPN/nerf_rpn/run_rpn.py", line 788, in eval
    output_list, losses, scores = self.model(
  File "/home/kameel/anaconda3/envs/nerfrpn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kameel/Repos/NeRF_RPN/nerf_rpn/model/nerf_rpn.py", line 213, in forward
    proposals, level_index, proposal_losses, scores = self.rpn(
  File "/home/kameel/anaconda3/envs/nerfrpn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kameel/Repos/NeRF_RPN/nerf_rpn/model/rpn.py", line 508, in forward
    proposals = self.box_coder.decode_list(pred_bbox_deltas_unflattened, non_cat_anchors)
  File "/home/kameel/Repos/NeRF_RPN/nerf_rpn/model/coder/base_bbox_coder.py", line 74, in decode_list
    pred_boxes = self.decode_single(delta, boxes)
  File "/home/kameel/Repos/NeRF_RPN/nerf_rpn/model/coder/midpoint_offset_coder.py", line 45, in decode_single
    decoded_bboxes = delta_sp2bbox(anchors, pred_deltas, self.means, self.stds, wh_ratio_clip)
  File "/home/kameel/Repos/NeRF_RPN/nerf_rpn/model/coder/midpoint_offset_coder.py", line 220, in delta_sp2bbox
    obboxes_2d = rectpoly2obb(rectpolys).flatten(-2) # (x, y, w, h, theta)
  File "/home/kameel/Repos/NeRF_RPN/nerf_rpn/model/coder/misc.py", line 33, in rectpoly2obb
    rotate_polys = torch.matmul(center_polys, Matrix.transpose(-1, -2))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
```
GPU Info:
GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU (UUID: GPU-96db4088-8067-cb6d-2191-7588c94508cb)

Nvidia Driver:
NVRM version: NVIDIA UNIX x86_64 Kernel Module  470.223.02  Sat Oct  7 15:39:11 UTC 2023

GCC: 
GCC version:  gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)

CUDA:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

**Comment by kameel2311** [comment]
Moreover, I tried removing the --boxes_path from the bash script and causes the code to no longer find the boxes as I had to hard code self.boxes_path = None in the datasets.py file. Code ran into the same error as mentioned above

**Comment by kameel2311** [comment]
SOLVED: So the input dimentionality is of no issue, as I made a test code and works when variables are on CPU , breaks when transfered to GPU, hence likely a CUDA issue. Therefore I switched from CUDA 11.2 to 12.2 and now it works !
